language: php

dist: xenial

services:
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - DB=PGSQL

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: RECIPE_VERSION=4.5.x-dev PHPUNIT_TEST=postgresql PHPCS_TEST=1
    - php: 7.1
      env: RECIPE_VERSION=4.5.x-dev PHPUNIT_TEST=framework
    - php: 7.2
      env: RECIPE_VERSION=4.6.x-dev PHPUNIT_TEST=framework
    - php: 7.3
      env: RECIPE_VERSION=4.6.x-dev PHPUNIT_TEST=framework
    - php: 7.4
      env: RECIPE_VERSION=4.6.x-dev PHPUNIT_TEST=postgresql
    - php: 7.4
      env: RECIPE_VERSION=4.x-dev PHPUNIT_TEST=framework

before_script:
# Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - export PATH=~/.composer/vendor/bin:$PATH
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer dependencies
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:$RECIPE_VERSION
  # Fix for running phpunit 5 on php 7.4+
  - composer require --no-update sminnee/phpunit-mock-objects:^3
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile
  - if [[ $PHPCS_TEST ]]; then composer global require squizlabs/php_codesniffer:^3 --prefer-dist --no-interaction --no-progress --no-suggest -o; fi

script:
  - if [[ $PHPUNIT_TEST == postgresql ]]; then vendor/bin/phpunit ./tests; fi
  - if [[ $PHPUNIT_TEST == framework ]]; then vendor/bin/phpunit ./vendor/silverstripe/framework/tests/php; fi
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi
